name: "setup"
description: "Perform checkout and python setup for config repositories"
inputs:
  ref:
    description: "Git ref to check out"
    required: true
  token:
    description: "Github token used in checkout"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email checkpad-robot@users.noreply.github.com
        git config --global user.name "checkpad-robot"
      shell: bash

    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        ref: ${{ inputs.ref }} # Checkout by branch makes actions robust against reruns
        submodules: recursive

    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: scripts/requirements.txt

    - run: pip install -r scripts/requirements.txt
      shell: bash
    
    - run: git pull # Changes might have come in during python setup
      shell: bash
