name: "setup"
description: "Perform checkout and python setup for config repositories"
inputs:
  ref:
    description: "Git ref to check out"
    required: true

  token:
    description: "Github token used in checkout"
    required: true

  requirements_file:
    description: "Path to the requirements file"
    required: false
    default: scripts/requirements.txt

runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email checkpad-robot@users.noreply.github.com
        git config --global user.name "checkpad-robot"
      shell: bash

    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        ref: ${{ inputs.ref }} # Checkout by branch makes actions robust against reruns
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: pip install -r ${{ inputs.requirements_file }}
      shell: bash
    
    - run: git pull # Changes might have come in during python setup
      shell: bash
