name: "Setup"
description: "TODO"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email checkpad-robot@users.noreply.github.com
        git config --global user.name "checkpad-robot"
      shell: bash

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        fetch-depth: 0
        ref: admintool/dev-live
        submodules: recursive

    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: scripts/requirements.txt

    - run: pip install -r scripts/requirements.txt
      shell: bash
